<<<<<<< HEAD
baseURL      = "https://pics.mcdonough.host"
title        = "McDonough Host"
[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"
=======
[module]
[module.hugoVersion]
    extended = true
    min = '0.121.2'
>>>>>>> 87b3ea7996791682e9d8bd9facae7d1d66f1e8dc
